/*
 * Copyright 2010-2019 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.nj2k.inference.nullability;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("nj2k/testData/inference/nullability/inference")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class NullabilityInferenceTestGenerated extends AbstractNullabilityInferenceTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
    }

    public void testAllFilesPresentInInference() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("nj2k/testData/inference/nullability/inference"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("compareWithNull.kt")
    public void testCompareWithNull() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/compareWithNull.kt");
    }

    @TestMetadata("forcedNullability.kt")
    public void testForcedNullability() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/forcedNullability.kt");
    }

    @TestMetadata("functionTypeParameterNullability.kt")
    public void testFunctionTypeParameterNullability() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/functionTypeParameterNullability.kt");
    }

    @TestMetadata("functions.kt")
    public void testFunctions() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/functions.kt");
    }

    @TestMetadata("loops.kt")
    public void testLoops() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/loops.kt");
    }

    @TestMetadata("nullAsAssignment.kt")
    public void testNullAsAssignment() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/nullAsAssignment.kt");
    }

    @TestMetadata("nullAsInitializer.kt")
    public void testNullAsInitializer() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/nullAsInitializer.kt");
    }

    @TestMetadata("smartCast.kt")
    public void testSmartCast() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/smartCast.kt");
    }

    @TestMetadata("spreadExpression.kt")
    public void testSpreadExpression() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/spreadExpression.kt");
    }

    @TestMetadata("superMethod.kt")
    public void testSuperMethod() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/superMethod.kt");
    }

    @TestMetadata("typeCast.kt")
    public void testTypeCast() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/typeCast.kt");
    }

    @TestMetadata("typeParameters.kt")
    public void testTypeParameters() throws Exception {
        runTest("nj2k/testData/inference/nullability/inference/typeParameters.kt");
    }
}
